language: php
dist: trusty
env:
  - WP_VERSION=latest
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
jobs:
  include:
    - stage: e2e
      name: "E2E Tests."
      php: 7.1
      script:
        - npm run cypress:run
    - stage: test
      php: 7.0
      name: "PHP Code sniffer lint."
      script:
        - composer install
        - composer run-script lint
    - php: 5.3
      dist: precise
      env: WP_VERSION=5.1.1
      script:
        - ./bin/run-unit-tests.sh
    - php: 5.4
      env: WP_VERSION=5.1.1
      script:
        - ./bin/run-unit-tests.sh
    - php: 5.5
      env: WP_VERSION=5.1.1
      script:
        - ./bin/run-unit-tests.sh
    - php: 5.6
      script:
        - ./bin/run-unit-tests.sh
    - php: 7.0
      script:
        - ./bin/run-unit-tests.sh
    - php: 7.1
      script:
        - ./bin/run-unit-tests.sh

    - stage: deploy
      before_install:
        - nvm install && nvm use
        - npm install npm -g
      script:
        - npm install || exit 1
        - npm run semantic-release || exit 1

stages:
  - name: e2e
    if: head_branch = development and type = "pull_request" and repo = "Codeinwp/ti-onboarding"
  - name: deploy
    if: branch = master and type != "pull_request" and repo = "Codeinwp/ti-onboarding"
  - name: test
    if: type = "pull_request"
